version: '3.3'

services:
  stable-diffusion:
    container_name: sd
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - .:/sd
      - ./outputs:/sd/outputs
      - micromamba_env:/root/micromamba
      - root_profile:/root
    ports:
      - '7860:7860'
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

volumes:
  micromamba_env:
  root_profile:
